### ISSUE TITLE
Problems 

### ISSUE THREAD

**Issue by AZDane** [dcshoecomp/homeassistant-cox#4]
Don't know if related, but after upgrading HA to 0.112.1 I'm getting the following error:

`Log Details (ERROR)
Logger: homeassistant.components.sensor
Source: custom_components/cox_sensor/sensor.py:104
Integration: Sensor (documentation, issues)
First occurred: 11:23:48 PM (1 occurrences)
Last logged: 11:23:48 PM

Error while setting up cox_sensor platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 292, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 451, in _async_add_entity
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 290, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 314, in _async_write_ha_state
    sstate = self.state
  File "/config/custom_components/cox_sensor/sensor.py", line 104, in state
    return self._state
AttributeError: 'cox_sensor' object has no attribute '_state'`

**Comment by chris8837** [comment]
Looks like something was redone on Cox Website.  I have a link to the original sensor.  Someone therefigured it out but in docker?  That's not something I use.

https://github.com/ntalekt/Cox_Data_Usage/issues

**Comment by dcshoecomp** [comment]
New release v0.1.1 with both working switch and sensor.
